name: Java workflow with gradle

on:
  push:
    branches: 
             main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: verify java installation
      run: java --version
      
    - name: verify gradle installation  
      run: gradle --version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: gradle build
    - run: ls ./build/libs
    - name: upload the file
      uses: actions/upload-artifact@v2
      with:
         path: ./build/libs
         retention-days: 5
